exports.data=[
    {
        name:'Agarwal Residence',
        address:'Shastri Nagar,Andheri',
        location:'Lucknow',
        price:2200,
        moveInDate:'2021-8-11',
        propertyType:'House',
        area:2200,
        beds:4,
        bathrooms:4,     
    },
    {
        name:'Sharma Residence',
        address:'Ashirvad Ind Estate, Saraspur',
        location:'Lucknow',
        price:1500,
        moveInDate:'2022-10-12',
        propertyType:'House',
        area:4000,
        beds:2,
        bathrooms:1,     
    },
    {
        name:'Alok Bhavan',
        address:'Arya Vidya Mandir Marg, Juhu',
        location:'New Delhi',
        price:3000,
        moveInDate:'2022-11-12',
        propertyType:'House',
        area:1000,
        beds:2,
        bathrooms:2,     
    },
    {
        name:'Aman Home',
        address:'8/7, Kirti Nagar Area',
        location:'New Delhi',
        price:2500,
        moveInDate:'2023-1-12',
        propertyType:'House',
        area:3000,
        beds:3,
        bathrooms:4,     
    },
    {
        name:'Workable Space',
        address:' Lbs Marg, Sita Vihar,navpada, Thane',
        location:'Mumbai',
        price:1800,
        moveInDate:'2022-9-12',
        propertyType:'Office',
        area:2000,
        beds:1,
        bathrooms:2,     
    },
    {
        name:'Developer Heaven',
        address:'5th Main, Sampangirama Nagar',
        location:'Lucknow',
        price:11520,
        moveInDate:'2022-11-12',
        propertyType:'Office',
        area:6000,
        beds:2,
        bathrooms:1,     
    },
    {
        name:'Jain Residence',
        address:'E 25, Defence Colony',
        location:'New Delhi',
        price:8400,
        moveInDate:'2022-10-12',
        propertyType:'Industry',
        area:7000,
        beds:4,
        bathrooms:4,     
    },
    {
        name:'Nasik Harbor',
        address:'7th Road, Santacruz',
        location:'Mumbai',
        price:4000,
        moveInDate:'2022-12-12',
        propertyType:'Industry',
        area:3000,
        beds:1,
        bathrooms:1,     
    },
    {
        name:'Thane Field',
        address:'H S Joshi Marg, Thane',
        location:'Mumbai',
        price:900,
        moveInDate:'2022-2-12',
        propertyType:'Industry',
        area:2000,
        beds:5,
        bathrooms:2,     
    },
    {
        name:'Designer Ave',
        address:'Sant Sena Maharaj Marg, Kailash Colony',
        location:'New Delhi',
        price:2300,
        moveInDate:'2022-11-12',
        propertyType:'Office',
        area:3000,
        beds:3,
        bathrooms:3,     
    },
    {
        name:'Tyagi Residence',
        address:'14 Street Cred',
        location:'Mumbai',
        price:5000,
        moveInDate:'2022-12-12',
        propertyType:'House',
        area:4000,
        beds:7,
        bathrooms:4,     
    },
    {
        name:'Rai Residence',
        address:'Esplanade Road, Lajpat Rai Market',
        location:'New Delhi',
        price:1300,
        moveInDate:'2022-11-12',
        propertyType:'House',
        area:2000,
        beds:1,
        bathrooms:3,     
    },
    {
        name:'Chicken Commerce',
        address:'Morgan Road 12',
        location:'Lucknow',
        price:4500,
        moveInDate:'2022-12-12',
        propertyType:'Industry',
        area:10000,
        beds:5,
        bathrooms:6,     
    },
    {
        name:'Easy home',
        address:' Main Ajmal Khan Road, Karol Bagh',
        location:'New Delhi',
        price:2000,
        moveInDate:'2022-12-12',
        propertyType:'House',
        area:10000,
        beds:5,
        bathrooms:6,     
        
    },
    {
        name:'Comfy Office',
        address:'Jammu Road 15',
        location:'Lucknow',
        price:2500,
        moveInDate:'2022-11-12',
        propertyType:'Office',
        area:10000,
        beds:5,
        bathrooms:6,     
    },
    {
        name:'Geeta Bhavan',
        address:'Morgle Road 15',
        location:'Mumbai',
        price:7000,
        moveInDate:'2022-12-12',
        propertyType:'House',
        area:12000,
        beds:8,
        bathrooms:6,     
        
    },
    {
        name:'Mind Palace',
        address:'Jammu Road 15',
        location:'New Delhi',
        price:3500,
        moveInDate:'2022-11-12',
        propertyType:'Office',
        area:10000,
        beds:5,
        bathrooms:6,     
    },
    {
        name:'Cottage Cheese',
        address:'C 15 Sector 2',
        location:'Lucknow',
        price:7500,
        moveInDate:'2022-11-12',
        propertyType:'Industry',
        area:10000,
        beds:2,
        bathrooms:1,     
    },
];